Main:
  Aliases:
    - "check"
    - "checker"
  PlDescr: "Player checker."
  blockmove: false
  blockdrop: true
  quitpermban: true
  ConsoleExec: true
  checkroom: ""

SubCommands:
  check:
    name: "-check"
    perm: "checker.check"
    admTp: true
  clear:
    name: "-clear"
    perm: "checker.clear"
  permban:
    enable: true
    name: "-perm"
    perm: "checker.ban"
    ConsoleExec: true
    exccom: "ban %PLAYER% cheaty/%ADM%"
  tempban:
    enable: true
    name: "-temp"
    perm: "checker.ban"
    ConsoleExec: true
    exccom: "tempban %PLAYER% %TIME% cheaty/%ADM%"
  wspban:
    enable: true
    name: "-wsp"
    perm: "checker.ban"
    ConsoleExec: true
    exccom: "ban %PLAYER% %TIME% Brak wspolpracy/%ADM%"
  loc:
    name: "-loc"
    perm: "checker.loc"
    set:
      name: "set"
      perm: "checker.loc.set"
    get:
      name: "get"
      perm: "checker.loc.get"
#  set:
#    enable: true
#    name: "-cset"
#    perm: "checker.set"
#  get:
#    enable: true
#    name: "-cget"
#    perm: "checker.get"